// Alle norske kommuner (356 stk, per 2026)
// ASCII-versjon av kommunenavn (ø→o, å→a, æ→ae) for å unngå encoding-problemer i URL-er og kode.
// Brukes i søkeskjemaer og filtre på hele nettstedet.
export const ALLE_KOMMUNER = [
  'Alstahaug','Alta','Alvdal','Alver','Ammot','Andoy','Aremark','Arendal','Asker',
  'Askvoll','Askoy','Aure','Aurland','Aurskog-Holand','Austrheim','Austevoll',
  'Averoy','Aukra','Afjord','Al',
  'Bamble','Balsfjord','Bardu','Batsfjord','Beiarn','Bergen','Berlevag','Bindal',
  'Birkenes','Bjorkreim','Bjornafjorden','Bodo','Bokn','Bomlo','Bremanger',
  'Bronnoy','Bygland','Bykle','Bo i Nordland','Bo i Telemark','Baerum',
  'Dovre','Drammen','Drangedal','Donna','Dyroy',
  'Eidfjord','Eidskog','Eidsvoll','Eigersund','Elverum','Enebakk','Engerdal',
  'Etne','Etnedal','Evenes','Evje og Hornnes',
  'Farsund','Fauske','Fedje','Fitjar','Fjaler','Fjord','Fla','Flakstad','Flatanger',
  'Flesberg','Flekkefjord','Folldal','Fredrikstad','Froland','Frogn','Frosta',
  'Froya','Fraena','Fyresdal',
  'Gamvik','Gausdal','Gildeskaal','Giske','Gjemnes','Gjerdrum','Gjerstad','Gjesdal',
  'Gjovik','Gloppen','Gol','Gran','Grane','Gratangen','Grimstad','Grong','Grue',
  'Gulen',
  'Hadsel','Halden','Hamaroy','Hamar','Hammerfest','Haram','Hareid','Harstad',
  'Hasvik','Hattfjelldal','Haugesund','Heim','Hemsedal','Hemnes',
  'Heroy i More og Romsdal','Heroy i Nordland','Hitra','Hjartdal','Hjelmeland',
  'Hol','Hole','Holmestrand','Holtalen','Horten','Hurdal','Hustadvika','Hvaler',
  'Hyllestad','Hoyanger','Hoylandet','Ha',
  'Ibestad','Inderoy','Indre Fosen','Indre Ostfold','Iveland',
  'Jevnaker',
  'Kafjord','Karmoy','Karlsoy','Karasjok','Kautokeino','Kinn','Klepp','Kongsberg',
  'Kongsvinger','Kragero','Kristiansand','Kristiansund','Krodsherad','Kvam',
  'Kvaefjord','Kvaenangen','Kvinesdal','Kvinnherad','Kviteseid','Kvitsoy',
  'Larvik','Lavangen','Lebesby','Leirfjord','Leka','Lesja','Levanger','Lier',
  'Lierne','Lillesand','Lillehammer','Lillestrom','Lindesnes','Lodingen','Lom',
  'Loppa','Loten','Lund','Lunner','Luroy','Luster','Lyngen','Lyngdal','Laerdal',
  'Malselv','Malvik','Marker','Masfjorden','Melhus','Meloy','Meraker',
  'Midt-Telemark','Midtre Gauldal','Modalen','Modum','Molde','Moskenes','Moss',
  'Masoy',
  'Namsos','Namsskogan','Nannestad','Narvik','Nes','Nesbyen','Nesna','Nesodden',
  'Nesseby','Nissedal','Nittedal','Nome','Nord-Aurdal','Nord-Fron','Nord-Odal',
  'Nordkapp','Nordre Follo','Nordre Land','Nordreisa','Nore og Uvdal','Notodden',
  'Naeroysund',
  'Oppdal','Orkland','Osen','Oslo','Osteroy','Overhalla',
  'Porsanger','Porsgrunn',
  'Rakkestad','Ralingen','Rana','Randaberg','Rauma','Rade','Rendalen','Rennebu',
  'Ringebu','Ringerike','Ringsaker','Risor','Rodoy','Rollag','Roros','Rost',
  'Royrvik',
  'Salangen','Saltdal','Samnanger','Sande','Sandefjord','Sandnes','Sarpsborg',
  'Sauda','Sel','Selbu','Seljord','Senja','Sigdal','Siljan','Sirdal','Skaun',
  'Skien','Skiptvet','Skjaak','Skjervoy','Smola','Snasa','Sogndal','Sokndal',
  'Sola','Solund','Somna','Sor-Aurdal','Sor-Fron','Sor-Odal','Sor-Varanger',
  'Sorfold','Sorreisa','Sortland','Stad','Stange','Stavanger','Steigen',
  'Steinkjer','Stjordal','Stor-Elvdal','Stord','Storfjord','Strand','Stranda',
  'Stryn','Sula','Suldal','Sunndal','Surnadal','Sveio','Sykkylven',
  'Tana','Time','Tingvoll','Tinn','Tjeldsund','Tokke','Tolga','Tonsberg',
  'Trana','Tromso','Trondheim','Trysil','Tvedestrand','Tynset','Tysnes','Tysvar',
  'Ullensaker','Ullensvang','Ulstein','Ulvik','Utsira',
  'Vadso','Vaksdal','Valle','Vang','Vanylven','Vardo','Vega','Vegarshei','Vefsn',
  'Vennesla','Verdal','Vestby','Vestnes','Vestre Slidre','Vestre Toten',
  'Vestvagoy','Vevelstad','Vik','Vindafjord','Vinje','Volda','Voss','Vaagan',
  'Vaga','Vaaler i Innlandet','Vaaler i Vestfold','Vaeroy',
  'Oksnes','Orland','Orsta','Ostre Slidre','Ostre Toten',
  'Ovre Eiker','Oyer','Oygarden','Oystre Slidre',
  'Alesund','Amli','Amot','Ardal','As','Aseral','Asnes',
].sort((a, b) => a.localeCompare(b, 'nb-NO'))
